// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import (
	gin "github.com/gin-gonic/gin"
	mock "github.com/stretchr/testify/mock"
)

// IUsersController is an autogenerated mock type for the IUsersController type
type IUsersController struct {
	mock.Mock
}

// Create provides a mock function with given fields: c
func (_m *IUsersController) Create(c *gin.Context) {
	_m.Called(c)
}

// Get provides a mock function with given fields: c
func (_m *IUsersController) Get(c *gin.Context) {
	_m.Called(c)
}

// Remove provides a mock function with given fields: c
func (_m *IUsersController) Remove(c *gin.Context) {
	_m.Called(c)
}

// Update provides a mock function with given fields: c
func (_m *IUsersController) Update(c *gin.Context) {
	_m.Called(c)
}

type mockConstructorTestingTNewIUsersController interface {
	mock.TestingT
	Cleanup(func())
}

// NewIUsersController creates a new instance of IUsersController. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewIUsersController(t mockConstructorTestingTNewIUsersController) *IUsersController {
	mock := &IUsersController{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
