service:
  port: ":8080"

database:
  name: faceit
  host: 127.0.0.1
  port: 3306
  user: user
  pass: pass
  driver: mysql
  root_user: root
  root_pass: root

redis:
  host: ["127.0.0.1:6379"]
  pool_timeout_in_seconds: 120
  idle_timeout_in_seconds: 600
  read_timeout_in_seconds: 120
  write_timeout_in_seconds: 60